# Generated by Django 3.1.3 on 2021-07-10 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_item2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item2',
        ),
    ]
